---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  solo_rb:
    ssl_verify_mode: verify_peer

platforms:
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
  - name: ubuntu-16.04
    run_list:
      - recipe[apt]

suites:
  - name: default_composer
    run_list:
      - recipe[phpunit::default]
    attributes:
      phpunit:
        install_method: composer
  - name: default_phar
    run_list:
      - recipe[phpunit::default]
    attributes:
      phpunit:
        install_method: phar
